name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: self-hosted

    steps:
      - name: Pull frontend Docker image
        run: sudo docker pull samyampradhan/bookstore-frontend:latest

      - name: Delete old frontend container
        run: sudo docker rm -f bookstore-frontend-container || true

      - name: Run frontend container
        run: sudo docker run -d -p 80:80 --name bookstore-container samyampradhan/bookstore-frontend:latest